project_name: arelo
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: arelo
    binary: arelo
    ldflags:
    #  - -s -w
    #  - -X main.Version={{.Version}}
    #  - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
